freebsd_instance:
  cpu: 4
  memory: "4"

task:
    # Basic metadata:
    name: hello_world

    # The build machine:
    freebsd_instance:
        image_family: freebsd-12-1

    # No environment variables provided.

    # Instructions:
    test_script: echo "hello world"
